### ISSUE TITLE
Button-card template 'custom_card_andyblac_room' is missing!

### ISSUE THREAD

**Issue by shingetsu00** [andyblac/UI-Minimalist-Custom-Cards#26]
Hi, I'm having some problems

![Immagine 2024-10-02 100418](https://github.com/user-attachments/assets/69bee8d2-5064-4405-b9b9-d0640fb38844)

I followed all the instructions on this link:

https://github.com/andyblac/UI-Minimalist-Custom-Cards/blob/main/README.md 

I've done the steps twice, uninstalling and reinstalling everything, but nothing works

![Immagine 2024-10-02 100556](https://github.com/user-attachments/assets/18d2dbca-fed3-492d-98e8-cb42f3a9b814)

**Comment by andyblac** [comment]
did you reload Minimalist UI after uploading folders. 

goto Developer Tool -- >. YAML, scroll down to minimalist ui and reload it.
(I should have that in the read me, my mistake sorry)

**Comment by shingetsu00** [comment]
I reload all, turned everything off and on again but it doesn't work, same error

**Comment by andyblac** [comment]
are the other minimalist card working ?

**Comment by shingetsu00** [comment]
nothing, same error

**Comment by shingetsu00** [comment]
@andyblac on the file ui-lovelace.yaml  what is the correct path to enter here? I've been trying to solve it for days, maybe it's this part but I don't understand


button_card_templates: !include ....

**Comment by andyblac** [comment]
should be default from minimalist install

`button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"`

**Comment by shingetsu00** [comment]
They had a similar problem on a forum and by changing this they solved it. But nothing, it gives me the same error it's impossible for me

**Comment by shingetsu00** [comment]
I did everything with this other option in the video and solved it https://www.youtube.com/watch?v=RSQwxuAmYfE&t=192s&ab_channel=MySmartHome
