### ISSUE TITLE
Feature requsest: Conditional appearence of the sensor object

### ISSUE THREAD

**Issue by FelixArndt** [andyblac/UI-Minimalist-Custom-Cards#6]
Hello Andy,

is it possible to hide them and only let them appear on a condition? E. g. for Window- or Motionsensors, only show them, when they are “on”.

Thanks in advance & keep up the good work!
Felix

**Comment by andyblac** [comment]
I'll take a look should be pretty easy to do.

**Comment by andyblac** [comment]
this https://github.com/andyblac/UI-Minimalist-Custom-Cards/commit/f74520b2f05a89840eade130ed4f0ce78150ef39 should do what you asked for, please test, and report back.

**Comment by FelixArndt** [comment]
Perfect, thank you!
