### ISSUE TITLE
Features request: camera icon to the right of the name

### ISSUE THREAD

**Issue by mon3y78** [andyblac/UI-Minimalist-Custom-Cards#8]
it would be nice to add an icon to the right of the name to call the room camera.  Can anyone experienced in grids help?)
![IMG_20231114_153247.jpg](https://github.com/andyblac/UI-Minimalist-Custom-Cards/assets/45080867/5c5c06c3-b442-4635-9433-b80b9f83374d)

**Comment by mon3y78** [comment]
https://github.com/mon3y78/UI-Minimalist-Custom-Cards/blob/patch-2/custom_cards/custom_card_andyblac_room/custom_card_andyblac_room.yaml

**Comment by andyblac** [comment]
create a Pull Request against the dev branch, and I take a look.

**Comment by andyblac** [comment]
added commit https://github.com/andyblac/UI-Minimalist-Custom-Cards/commit/e96999e455ad14fab82bcb74b035ce26f2f0faac
